"""renaming birthday to hbd

Revision ID: 964f727c0a01
Revises: 791279dd0760
Create Date: 2024-09-22 23:08:17.053954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '964f727c0a01'
down_revision = '791279dd0760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('hbd', sa.DateTime(), nullable=True))
    op.drop_column('students', 'birthday')
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('birthday', sa.DATETIME(), nullable=True))
    op.drop_column('students', 'hbd')
    # ### end Alembic commands ###
